// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace CES.DataTier.Models
{
    public partial class DebtTicket
    {
        public DebtTicket()
        {
            Invoke = new HashSet<Invoke>();
            Order = new HashSet<Order>();
        }

        public int Id { get; set; }
        public string? Name { get; set; }
        public double Total { get; set; }
        public int? Status { get; set; }
        public string? InfoPayment { get; set; }
        public int CompanyId { get; set; }
        public DateTime? CreatedAt { get; set; }
        public DateTime? UpdatedAt { get; set; }

        public virtual Company Company { get; set; } = null!;
        public virtual ICollection<Invoke> Invoke { get; set; }
        public virtual ICollection<Order> Order { get; set; }
    }
}