// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace CES.DataTier.Models
{
    public partial class Discount
    {
        public Discount()
        {
            Product = new HashSet<Product>();
        }

        public int Id { get; set; }
        public int? Type { get; set; }
        public double? Amount { get; set; }
        public int? Status { get; set; }
        public string? ImageUrl { get; set; }
        public DateTime? ExpiredDate { get; set; }

        public virtual ICollection<Product> Product { get; set; }
    }
}