// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace CES.DataTier.Models
{
    public partial class Group
    {
        public Group()
        {
            GroupAccount = new HashSet<GroupAccount>();
        }

        public Guid Id { get; set; }
        public string? Name { get; set; }
        public int? Status { get; set; }
        public string? ImageUrl { get; set; }
        public string? Description { get; set; }
        public int CompanyId { get; set; }
        public DateTime? CreatedAt { get; set; }
        public DateTime? UpdatedAt { get; set; }
        public Guid? CreatedBy { get; set; }
        public Guid? UpdatedBy { get; set; }

        public virtual Company Company { get; set; } = null!;
        public virtual ICollection<GroupAccount> GroupAccount { get; set; }
    }
}