// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace CES.DataTier.Models
{
    public partial class GroupAccount
    {
        public Guid Id { get; set; }
        public Guid? AccountId { get; set; }
        public Guid? GroupId { get; set; }

        public virtual Account? Account { get; set; }
        public virtual Group? Group { get; set; }
    }
}