// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace CES.DataTier.Models
{
    public partial class Order
    {
        public Order()
        {
            OrderDetail = new HashSet<OrderDetail>();
        }

        public Guid Id { get; set; }
        public double Total { get; set; }
        public string? Notes { get; set; }
        public string? Address { get; set; }
        public int? Status { get; set; }
        public int? DebtStatus { get; set; }
        public DateTime? CreatedAt { get; set; }
        public DateTime? UpdatedAt { get; set; }
        public Guid AccountId { get; set; }
        public int? DebtId { get; set; }

        public virtual Account Account { get; set; } = null!;
        public virtual DebtTicket? Debt { get; set; }
        public virtual ICollection<OrderDetail> OrderDetail { get; set; }
    }
}