// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace CES.DataTier.Models
{
    public partial class Order
    {
        public Order()
        {
            DebtNotes = new HashSet<DebtNotes>();
            OrderDetail = new HashSet<OrderDetail>();
            Transaction = new HashSet<Transaction>();
        }

        public Guid Id { get; set; }
        public double? Total { get; set; }
        public string? Note { get; set; }
        public string? Address { get; set; }
        public DateTime? UpdatedAt { get; set; }
        public DateTime? CreatedAt { get; set; }
        public int? Status { get; set; }
        public string? Code { get; set; }
        public int? DebtStatus { get; set; }
        public Guid? AccountId { get; set; }

        public virtual Account? Account { get; set; }
        public virtual ICollection<DebtNotes> DebtNotes { get; set; }
        public virtual ICollection<OrderDetail> OrderDetail { get; set; }
        public virtual ICollection<Transaction> Transaction { get; set; }
    }
}