// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace CES.DataTier.Models
{
    public partial class Product
    {
        public Product()
        {
            OrderDetail = new HashSet<OrderDetail>();
        }

        public Guid Id { get; set; }
        public double Price { get; set; }
        public int Quantity { get; set; }
        public string? Name { get; set; }
        public int? Status { get; set; }
        public string? Description { get; set; }
        public DateTime? CreatedAt { get; set; }
        public DateTime? UpdatedAt { get; set; }
        public int CategoryId { get; set; }
        public int? DiscountId { get; set; }
        public string? ImageUrl { get; set; }

        public virtual Category Category { get; set; } = null!;
        public virtual Discount? Discount { get; set; }
        public virtual ICollection<OrderDetail> OrderDetail { get; set; }
    }
}