# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Continuous Deployment .NET

on:
  push:
  pull_request:
    branches: ["main", "develop"]

env:
  DOTNET_VERSION: "6.0.x"
  ARTIFACT_NAME: "api"

jobs:
  build:
    if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop' }}
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ["6.0.x"]
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies
        run: dotnet restore
      - name: Publish
        if: github.ref == 'refs/heads/main'
        run: dotnet publish -c Release -o ${{ env.ARTIFACT_NAME }}
      - name: Publish Staging
        if: github.ref == 'refs/heads/develop'
        run: dotnet publish -c Release -o ${{ env.ARTIFACT_NAME }}
      - name: Share artifact inside workflow
        uses: actions/upload-artifact@v3
        with:
          name: api-github-actions-build
          path: ${{ env.ARTIFACT_NAME }}

  deploy:
    if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop' }}
    needs: [build]
    name: Deploy
    runs-on: windows-latest
    steps:
      - name: Get artifact
        uses: actions/download-artifact@v3
        with:
          name: api-github-actions-build
          path: ${{ env.ARTIFACT_NAME }}
      - name: Deploy Production
        if: github.ref == 'refs/heads/main'
        uses: garygrossgarten/github-action-scp@release
        with:
          local: ${{ env.ARTIFACT_NAME }}
          remote: C:\inetpub\wwwroot\CEsAPI
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
      - name: Deploy Staging
        if: github.ref == 'refs/heads/develop'
        uses: garygrossgarten/github-action-scp@release
        with:
          local: ${{ env.ARTIFACT_NAME }}
          remote: C:\inetpub\wwwroot\dev\CEsAPI
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
